audioteca/urls.py
from django.urls import path

from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index, name='index'),
    path('cantants/', views.CantantListView.as_view(), name='cantant'),
    path('cantants/<int:pk>', views.CantantDetailView.as_view(), name='cantant-detail'),

    path('albums/', views.AlbumListView.as_view(), name='album'),
    path('albums/<int:pk>', views.AlbumDetailView.as_view(), name='album-detail'),
    
    path('cançons/<int:pk>', views.CançoDetailView.as_view(), name='canço-detail'),

    path('generes/', views.GenereListView.as_view(), name='genere'),
    path('generes/<int:pk>', views.GenereDetailView.as_view(), name='genere-detail'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

musica/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('audioteca/', include('audioteca.urls')),
    path('', RedirectView.as_view(url='/audioteca/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

audioteca/models.py
from django.db import models
from django.urls import reverse

class Genere(models.Model):
    nom = models.CharField(max_length=200, help_text="Escriu el gènere de música (Ex: Pop, K-pop, Rock...)")

    def __str__(self):
        """
        Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administración)
        """
        return self.nom
    def get_absolute_url(self):
        return reverse('genere-detail', args=[str(self.id)])


class Album(models.Model):
    titol = models.CharField(max_length=200)

    cantant = models.ForeignKey('Cantant', on_delete=models.SET_NULL, null=True)

    duració = models.IntegerField(help_text="Escriu la duració total del àlbum")

    preu = models.IntegerField(help_text='Escriu el preu de l\'àlbum')

    generes = models.ManyToManyField(Genere, help_text="Selecciona un gènere per a aquest àlbum.")
    portada = models.ImageField(null=True)


    def __str__(self):
        return self.titol


    def get_absolute_url(self):
        return reverse('album-detail', args=[str(self.id)])
    
    def display_genere(self):
        return ', '.join([ generes.nom for generes in self.generes.all()[:3] ])
    
    display_genere.short_description = 'Genere'

    
class Cantant(models.Model):
    nom = models.CharField(max_length=100)
    cognom = models.CharField(max_length=100)
    naixement = models.DateField(null=True, blank=True)
    mort = models.DateField('mort', null=True, blank=True)
    descripcio = models.TextField(null = True, max_length=1000)
    premis = models.IntegerField(help_text="Escriu el número de premis que ha guanyat.")
    imatge = models.ImageField(null=True)

    def get_absolute_url(self):

        return reverse('cantant-detail', args=[str(self.id)])


    def __str__(self):
        return '%s, %s' % (self.cognom, self.nom)


class Canço(models.Model):
    titol = models.CharField(max_length=200)

    cantant = models.ForeignKey('Cantant', on_delete=models.SET_NULL, null=True)
    lletra = models.TextField(null = True)

    duració = models.IntegerField(help_text="Escriu la duració de al cançó")

    album = models.ForeignKey('Album', on_delete=models.SET_NULL, null=True)
    video = models.CharField(max_length=100000, null=True)


    def __str__(self):
        return self.titol

    def get_absolute_url(self):
        return reverse('canço-detail', args=[str(self.id)])

audioteca/views.py
from django.shortcuts import render
from django.views import generic
from .models import Cantant, Album, Canço, Genere

def index(request):
    num_albums=Album.objects.all().count()
    num_cançons=Canço.objects.all().count()
    num_cantants=Cantant.objects.count() 
    num_generes=Genere.objects.count()
    return render(
        request,
        'index.html',
        context={'num_albums':num_albums,'num_cançons':num_cançons,'num_cantants':num_cantants, 'num_generes':num_generes},
    )

class CantantListView(generic.ListView):
    model = Cantant

class CantantDetailView(generic.DetailView):
    model = Cantant

class AlbumListView(generic.ListView):
    model = Album

class AlbumDetailView(generic.DetailView):
    model = Album

class CançoDetailView(generic.DetailView):
    model = Canço

class GenereListView(generic.ListView):
    model = Genere

class GenereDetailView(generic.DetailView):
    model = Genere

audioteca/templates/audioteca/album_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="margePag">
    <h1>TÍTOL: {{ album.titol }}</h1>
    <div class="container-fluid">
        <div class="row">
          <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 mt-3">
            
                <div>
                    <h4>Cançons</h4>
                    <dl>
                    {% for canço in album.canço_set.all %}
                        <ul>
                            <li>
                                <dt><a href="{% url 'canço-detail' canço.pk %}">{{canço}}</a></dt>
                            </li>
                            <dd>{{canço.duració}} min</dd>
                        </ul>

                        {% empty %}
                        <p>Este àlbum no te cançons</p>
                    {% endfor %}
                    </dl>
                </div>
          </div>
  
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 mt-3">
            <div>
                <h4>Més info:</h4>
                <ul>
                    <li><strong>Preu: </strong> {{album.preu}}€</li>
                    <li><strong>Duració: </strong> {{ album.duració }} min</li>
                    {% for genere in album.generes.all %}
                        <li><strong>Gènere: </strong> <a href="{% url 'genere-detail' genere.pk %}">{{genere}}</a></li>
                        {% empty %}
                    <p>Este àlbum no te gènere</p>
                    {% endfor %}
                </ul>
            </div>
        </div>  
    </div>

</div>
    
{% endblock %}

audioteca/templates/audioteca/album_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="margePag">
    <h1>Àlbums registrats a la pàgina web</h1>
    <p>Endinsa't en la nostra col·lecció d'àlbums, amb detalls sobre {{ num_albums }} obres. Descobreix històries úniques i influències que han deixat empremta a la música.</p>



    <div class="container" style="margin-left: 0em; margin-bottom: 5em">
      <div class="row">      
        {% if album_list %}
          {% for album in album_list %}
            <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 mt-3">
              <div class="card text-center" style="height: 23em;">
                <div class="card-body">
                  <a href="{{ album.get_absolute_url }}"><img class="imgCard" src="/static/imatges/{{album.portada.name}}" alt=""></a>
                  <a href="{{ album.get_absolute_url }}"><h6 class="mt-3">{{album.titol}}</h4></a>
                </div>
              </div>
            </div>  
          {% endfor %}
        {% else %}
          <p>No hi han àlbums ara mateix registrats</p>
        {% endif %}
    </div>
  </div>


</div>
{% endblock %}

audioteca/templates/audioteca/cantant_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="margePag">
    <h1>NOM: {{ cantant.nom }}, {{ cantant.cognom }}</h1>
    <p>{{cantant.naixement}} - {% if cantant.mort %}{{cantant.mort}}{% endif %}</p>

    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-12 mt-3">

                <img src="/static/imatges/{{cantant.imatge.name}}"/>
            </div>
            <div class="col-xl-7 col-lg-7 col-md-7 col-sm-12 mt-3">
                <div>
                    {{cantant.descripcio}}
                </div>
            </div>
        </div>
    </div>

    <div style="margin-left:20px;margin-top:20px">

        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 mt-3">
                    <h4>Àlbums</h4>
                    <dl>
                    {% for album in cantant.album_set.all %}
                        <ul>
                            <li>
                                <dt><a href="{% url 'album-detail' album.pk %}">{{album}}</a></dt>
                            </li>
                            <dd>{{album.duració}} min</dd>
                        </ul>

                        {% empty %}
                        <p>Este cantant no té àlbums</p>
                    {% endfor %}
                    </dl>
                </div>

                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 mt-3">
                    <div style="margin-top: 20px;">
                        <h4>  Premis  </h4>
                        <p>Aquest cantant ha guanyat: {{cantant.premis}} premis.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
   
{% endblock %}

audioteca/templates/audioteca/cantant_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="margePag">
  <h1>Llista de cantants</h1>
  <p>Explora la rica paleta musical de la nostra audioteca al descobrir la diversitat de cantants destacats que formen part del nostre exclusiu repertori...</p>

  <div class="container" style="margin-left: 0em; margin-bottom:5em">
    <div class="row">      
      {% if cantant_list %}
        {% for cantant in cantant_list %}
          <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 mt-3">
            <div class="card text-center" style="height: 23em;">
              <div class="card-body">
                <a href="{{ cantant.get_absolute_url }}"><img class="imgCard" src="/static/imatges/{{cantant.imatge.name}}" alt=""></a>
                <a href="{{ cantant.get_absolute_url }}"><h6 class="mt-3">{{cantant.nom}} {{cantant.cognom}}</h6></a>
              </div>
            </div>
          </div>  
            {% endfor %}
      {% else %}
          <p>No hi ha cantants ara mateix registrats</p>
      {% endif %}
    </div>
  </div>
</div>

  

{% endblock %}

audioteca/templates/audioteca/canço_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="margePag">
    <h1>TÍTOL: {{ canço.titol }}</h1>
    <p><a href="{% url 'cantant-detail' canço.cantant.pk %}">{{canço.cantant}}</a></p>
    <div class="container-fluid">
        <div class="row">
          <div class="col-xl-5 col-lg-5 col-md-12 col-sm-12 mt-3">
            <div style="margin-left:20px;margin-top:20px">
                <h4>Lletra</h4>
                <pre>
                    {{canço.lletra}}
                </pre>
                
            </div>
          </div>
  
          <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mt-3">
            <h4>Més info:</h4>
            <ul>
                <li><strong>Album: </strong> <a href="{% url 'album-detail' canço.album.pk %}">{{canço.album}}</a></li>
                <li><strong>Duració: </strong> {{ canço.duració }} min</li>
            </ul>               
            <div style="margin-top: 2em;">
                <iframe width="560" height="315" src={{canço.video}} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>
        </div>  
    </div>
    


   

   


</div>
    
{% endblock %}

audioteca/templates/audioteca/genere_detail.html
{% extends "base_generic.html" %}

{% block content %}    
<div class="margePag">
    <h1>GÈNERE: {{ genere.nom }}</h1>


        <h4>Àlbums</h4>
        <dl>
        {% for album in genere.album_set.all %}
            <ul>
                <li>
                    <dt><a href="{% url 'album-detail' album.pk %}">{{album}}</a></dt>
                </li>
            </ul>

            {% empty %}
            <p>No hi ha cap àlbum registrat amb aquest gènere</p>
        {% endfor %}
        </dl>
</div>
{% endblock %}

audioteca/templates/audioteca/genere_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="margePag">
    <h1>GÈNERES</h1>
    <p>Descobreix la diversitat musical amb una àmplia gamma de gèneres, des del rock clàssic fins a les últimes tendències del pop. Informació detallada per a una exploració auditiva completa.</p>


    {% if genere_list %}
    <ul>

      {% for genere in genere_list %}
      <li>
        <a href="{{ genere.get_absolute_url }}">{{genere.nom}}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>No hi ha gèneres ara mateix registrats</p>
    {% endif %}
</div>
{% endblock %}

audioteca/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>AUDIOTECA</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">


</head>



  <header>
    <div class="container-fluid" style="background-color:black">
      <div class="row justify-content-between">
      
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
          <h1 id="titol">AUDIOTECA</h1>
        </div>      
        <div class="col-12">
          <nav class="navbar navbar-expand-sm navbar-light">
            <button class="navbar-toggler navbar-light bg-light" type="button" data-bs-toggle="collapse"
              data-bs-target="#opciones">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse navbar-light" style="margin-bottom: 0.81em;">
              <ul class="nav justify-content-end">
                <li><a class="enllaç" href="{% url 'index' %}">Pàgina principal </a></li>
                <li><a class="enllaç" href="{% url 'cantant' %}">Cantants </a></li>
                <li><a class="enllaç" href="{% url 'album' %}">Àlbums </a></li>
                <li><a class="enllaç"  href="{% url 'genere' %}">Gèneres </a></li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </header>

<body>
  <div class="container-fluid" style="margin-top: 2em;">
      <div class="col-lg-12">
      {% block content %}{% endblock %}
      {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">anterior</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">siguiente</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
      {% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

audioteca/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<div id="index">
  <h2>AUDIOTECA NATÀLIA</h2>

      <p>Benvinguts i benvingudes a la Audioteca de Natàlia, el teu destí definitiu per explorar l'univers apassionant de la música. En aquest rincó virtual, podràs plongar-te en un mar de coneixement sobre diversos cantants, descobrir les seves històries fascinants i explorar a fons els seus àlbums inoblidables. Des de les veus més icòniques fins als talents emergents, aquesta audioteca és un refugi per als amants de la música que busquen una experiència completa. Acompanya'ns en aquest viatge apassionant a través dels ritmes, les lletres i les melodies que han marcat èpoques i inspirat generacions.</p>
</div>


<section style="margin-top: 2em;">
  <h5>Contingut de la Audioteca</h5>

    <p style="margin-left:10em;">Explora l'ampli abast de la nostra audioteca, plena de diversitat musical i informació fascinant:</p>
      <div class="container">
        <div class="row">
          <div class="col-md">
            <div class="card text-center" style="height: 35em;">
              <div class="card-body">
                <a href="{% url 'album' %}"><img class="imgCard" src="audioteca/static/imatges/vinilos.jpg" alt=""></a>
                <h3 class="card-title mt-3">ÀLBUMS</h3>
                <p class="card-text"> Amb una col·lecció en expansió constant, oferim detalls detallats sobre {{ num_albums }} àlbums, des de clàssics eterns fins a les últimes produccions musicals.</p>
                <a href="{% url 'album' %}" class="btn" id="boto">Anar</a>
              </div>
            </div>
          </div>

          <div class="col-md">
            <div class="card text-center" style="height: 35em;">
              <div class="card-body">
                <a href="{% url 'album' %}"><img class="imgCard" src="audioteca/static/imatges/microfono.jpg" alt=""></a>
                <h3 class="card-title mt-3">CANTANTS</h3>
                <p class="card-text">
                  Descobreix més sobre els teus artistes preferits i els talents emergents que estan conquerint l'escenari musical global. Amb informació detallada sobre {{ num_cantants }} intèrprets.
                </p>
                <a href="{% url 'cantant' %}" class="btn" id="boto">Anar</a>
              </div>
            </div>
          </div>

          <div class="col-md">
            <div class="card text-center" style="height: 35em;">
              <div class="card-body">
                <img class="imgCard" src="audioteca/static/imatges/cançons.jpg" alt="">
                <h3 class="card-title mt-3">CANÇONS</h3>
                <p class="card-text"> Immergix-te en el món de les melodies amb la nostra extensa col·lecció de {{ num_cançons }} cançons. Des de èxits viralitzats fins a joies amagades, trobaràs una àmplia gamma de peces per satisfer tots els gustos musicals.</p>
              </div>
            </div>
          </div>
          <div class="col-md">
            <div class="card text-center" style="height: 35em;">
              <div class="card-body">
                <a href="{% url 'album' %}"><img class="imgCard" src="audioteca/static/imatges/generos.jpg" alt=""></a>
                <h3 class="card-title mt-3">GÈNERES</h3>
                <p class="card-text">Des del rock clàssic fins a les últimes tendències del pop, oferim una variada selecció de {{ num_generes }} gèneres musicals per a la teua exploració auditiva.</p>
                <a href="{% url 'genere' %}" class="btn" id="boto">Anar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<section>   

  <footer>
    <div class="container-fluid">
      <div class="row">
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12 mt-3" style="margin-left: 5em;">
          <h3>On estem?</h3>
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3092.511041328057!2d-0.44009582331758784!3d39.1858351716639!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd61b03094124c85%3A0x5bedacf9e7f72a04!2sInstitut%20d&#39;Ensenyament%20Secundari%20Sant%20Vicent%20Ferrer!5e0!3m2!1sen!2ses!4v1702630026213!5m2!1sen!2ses" width="200" height="150" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>

        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 mt-3">
          <h3 class="mb-3">Les nostres xarxes socials:</h3>
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" style="margin-right: 10%;" fill="currentColor"
            class="bi bi-facebook" viewBox="0 0 16 16">
            <path
              d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" style="margin-right: 10%;" fill="currentColor"
            class="bi bi-instagram" viewBox="0 0 16 16">
            <path
              d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-twitter"
            viewBox="0 0 16 16">
            <path
              d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
          </svg>
        </div>

        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 mt-3">
          <div class="container">
            <div class="row">
              <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <h3>AUDIOTECA</h3>
              </div>
            </div>
            <div class="row mt-3">
              <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                  class="bi bi-c-circle" viewBox="0 0 16 16">
                  <path
                    d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8Zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM8.146 4.992c-1.212 0-1.927.92-1.927 2.502v1.06c0 1.571.703 2.462 1.927 2.462.979 0 1.641-.586 1.729-1.418h1.295v.093c-.1 1.448-1.354 2.467-3.03 2.467-2.091 0-3.269-1.336-3.269-3.603V7.482c0-2.261 1.201-3.638 3.27-3.638 1.681 0 2.935 1.054 3.029 2.572v.088H9.875c-.088-.879-.768-1.512-1.729-1.512Z" />
                </svg>
              </div>
              <div class="col-xl-10 col-lg-10 col-md-10 col-sm-10">
                <p id="copyright">2023 - Natàlia Llanes Castell</p>
              </div>
            </div>
          </div>
        </div>
      </div>
  </footer>

{% endblock %}